version: "3"
services:
  # Service pour l'application Phoenix
  app:
    image: timemanager-app:latest
    command: /bin/sh entrypoint1.sh
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postresql://postgres:1234@db:5432/todolist
      - SECRET_KEY_BASE=Pi9Emv4b7mHawED5/6/R2mq7ux5svy8SXtGWDeUBJh7YGOkLHad0rsxQxUj1KNYd
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postresql/data
volumes:
  pgdata:
